---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RepositoryName:
    Type: String
  ParentServiceStack:
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  ServiceName:
    Description: 'The Name of the repository for storing docker images'
    Value: !Ref Repository
    Export:
      Name: !Sub '${ParentServiceStack}-RepositoryName'
